name = "ProtStructs"
uuid = "82f0014e-ea2f-4068-b3c4-8530e4b1bb6a"
authors = ["Bon Leif Amalla <bonleifamalla@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Chemfiles = "0.10"
StaticArrays = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
